### ISSUE TITLE
Couldnt connect to docker daemon

### ISSUE THREAD

**Issue by skarred14** [jpetazzo/dind#106]
I am trying to use the dind container as a boiler plate for installing additional software into the container. Upon running the container instance as suggested, after building from Dockerfile on github, as well as that on the Dockerhub. For testing, I am able to use the interactive (-i -t) mode with privileged flags to get a container running with root connected to the docker daemon. When I run the same in background mode (-d), the container stops 'Exit(1)'. As a work around, I ran, docker run -d --name d1 dind_image tail -f /dev/null. Although the container keeps running, upon using exec to get the shell mode: docker exec -it d1 /bin/bash, and typing in, docker ps -a in the shell of the container returns the error message: Couldnt connect to the docker daemon. Is the docker daemon active on this host? Questions:
1. Any suggestions as to how I can avoid the above during the testing process of adding more instructions to the dind Dockerfile?
2. As a custom extension test, I would like to create a custom user group to get access to docker daemon within the container. What is the equivalent of logging in and logging out of the container to ensure that the user is added after usermod and service restart?
3. In the documentation, there is a mention of linking a second container to control the main dind container. How can second container be used to control further operations on the main one?

**Comment by jpetazzo** [comment]
Hi!

I'm sorry, I'm not maintaining dind anymore, nor monitoring issues. 

I don't know how to address question 1. Re/ question 2, there is no "logging in and out" in a container. You can create the user/group (by editing the /etc/passwd and /etc/group files), commit, then when you'll start the new container, the user will be in the new groups. Re/ question 3, I'd suggest that you check [this blog post](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) explaining how to control Docker from within a container (it is the preferred method instead of Docker-in-Docker now). Thank you!
