### ISSUE TITLE
Make official, no copy/paste of dind script

### ISSUE THREAD

**Issue by jbeda** [jpetazzo/dind#22]
I'd like to use dind to support what I think might be a common flow:

1. Build some linux binaries
2. Build some docker images that include those binaries

I'd like to support development from the Mac with boot2docker.  I'm stuck with either copying binaries in and out of the boot2docker VM or do `dind`.  The fact that `dind` isn't an officially supported part of Docker and the script is copy/pasted/diverged from the `hack/dind` script in the Docker repo gives me pause.

So -- "feature request": Move this script to a canonical official place and make the Docker build process take a dependency on it.  Then others can follow that pattern with confidence.

**Comment by activars** [comment]
+1

**Comment by jpetazzo** [comment]
Aaaand I failed to allocate memory^W time slice. I'll try again soon but if someone has a better idea, I'd be happy to hear it!

**Comment by jpetazzo** [comment]
OK, I officially won't be able to take care of this. I wonder what should be the best approach. I think that Docker upstream prefers to vendor dependencies, so even if this were the official source, it would be vendored in the Docker repo somehow. I don't know what to do so I'll ask for @tianon's advice because they're wise.

**Comment by tianon** [comment]
@jpetazzo to be honest, this repo was so sporadically maintained that I've personally considered `hack/dind` inside the Docker repo to be the official "source of truth" as it were for how to do Docker in Docker (and it's the script I download anywhere I need to do Docker-in-Docker -- https://github.com/tianon/dockerfiles/blob/38ba24b92a7c5581e6a1cc51176c7e8ad1bcee92/dind/Dockerfile#L9-L10, although pinning that on an explicit Docker version and dind commit would be a very prudent idea)

**Comment by tianon** [comment]
(with no offense meant, obviously -- homies4lyfe :heart:)

**Comment by thaJeztah** [comment]
@tianon that's not really user-friendly, is it? Would splitting it out to, e.g., docker/dind be an option (and deprecating/redirecting this repo)?

The current status is confusing, i.e., what's the "best", "most up-to-date" dind?

**Comment by tianon** [comment]
If you want up-to-date bash-completion for Docker, it's in `docker/docker/contrib/completion/bash`.  If you want up-to-date Vim syntax highlighting for Docker, it's in `docker/docker/contrib/syntax/vim`.

In this case, what we're discussing is even simpler than those examples because it's a single script, so you can actually download just that one script without cloning the entire repo, so it seems pretty reasonable IMO that the canonical place for doing Docker-in-Docker lives in the Docker repository itself.

What I would like to do is make a more official "Docker-in-Docker" image, and have been discussing creating such a thing with several of the other Docker developers. :+1:

**Comment by jpetazzo** [comment]
+1!

What should I make with this one? I'm fine with marking it with a big
"DEPRECATED" flag and redirecting to the dind script in the Docker repo if
that helps.

On Fri, Jun 19, 2015 at 2:34 PM, Tianon Gravi <notifications@github.com>
wrote:

> If you want up-to-date bash-completion for Docker, it's in
> docker/docker/contrib/completion/bash. If you want up-to-date Vim syntax
> highlighting for Docker, it's in docker/docker/contrib/syntax/vim.
>
> In this case, what we're discussing is even simpler than those examples
> because it's a single script, so you can actually download just that one
> script without cloning the entire repo, so it seems pretty reasonable IMO
> that the canonical place for doing Docker-in-Docker lives in the Docker
> repository itself.
>
> What I would like to do is make a more official "Docker-in-Docker" image,
> and have been discussing creating such a thing with several of the other
> Docker developers. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpetazzo/dind/issues/22#issuecomment-113650256>.
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
"Is it safe to run applications into containers?"
http://www.slideshare.net/jpetazzo/docker-linux-containers-lxc-and-security

**Comment by lox** [comment]
Is there any possibility of making this repo just a thin wrapper around https://raw.githubusercontent.com/docker/docker/master/hack/dind? 

Ideally it would be a `library/dind` image, is that plausible?

**Comment by jpetazzo** [comment]
I totally agree with those ideas; is there documentation upstream explaining how to do dind? That would be the only missing step: merging/moving documentation upstream as well, and then replacing this repo with a link to the official upstream.

**Comment by thaJeztah** [comment]
According to https://github.com/docker/docker/pull/15596/, using dind is no longer required for docker 1.8 and above? So it may be just a matter of deprecating it altogether?

**Comment by jpetazzo** [comment]
Yes, totes! Updated README accordingly. Thanks!
