### ISSUE TITLE
Remove requirement of using volume for internal data

### ISSUE THREAD

**Issue by cancan101** [jpetazzo/dind#76]
When using non aufs file systems. For example : http://blog.cloud66.com/docker-with-overlayfs-first-impression/

**Comment by jpetazzo** [comment]
Hmm, I understand the reasoning, but I'd rather play safe and keep the volume so that it works by default for a large number of people (rather than "break by default if you use AUFS").

If people want the Docker state to be on the COW filesystem, they can reconfigure the daemon to use something else than `/var/lib/docker`.
