### ISSUE TITLE
Broken and out of date with Docker 1.8+

### ISSUE THREAD

**Issue by lox** [jpetazzo/dind#85]
Given https://github.com/docker/docker/pull/15596, is it worth either pointing to the latest https://raw.githubusercontent.com/docker/docker/master/hack/dind or just deleting this project entirely?

**Comment by jpetazzo** [comment]
Looks like there would be two options:

1) Running the `docker` official image with `-v /var/lib/docker` (and privileged mode), then `apk update && apk add iptables` and have fun

2) Possibly running busybox, ubuntu (or something with iptables already installed) and bind-mounting the Docker binary in it (didn't test, tho, also it needs dyn libs since now Docker ships as dynamic libs)

... Anyway it's not totally ready yet!

**Comment by jpetazzo** [comment]
... 3) Use `docker:dind` :D 

I updated the README to mention that. 

Thank you for bringing this to my attention!
