### ISSUE TITLE
No cgroup metrics for dind containers?

### ISSUE THREAD

**Issue by janeczku** [jpetazzo/dind#87]
Looking in `/sys/fs/cgroup/cpu/docker/` inside the dind container i see only IDs of containers running on the host docker daemon. It looks like for containers started within dind no cgroup metrics are created.  
Is this expected?

**Comment by jpetazzo** [comment]
Ah, that's because they should be nested!

On my machine, the cgroup hierarchy when using Docker-in-Docker looks like this:

```
/sys/fs/cgroup/cpu,cpuacct/system.slice/docker-a3c3…5bb5.scope/docker/788e…4174/
```

Where `a3c3…5bb5` is the ID of the Docker-in-Docker container (i.e. the ID of the `dind` container on my host) and `788e…4174` is the ID of the inner container.

Your exact paths might be different (my system is a bit ... *special*) but I think you should see them anyway.

Let me know!
