### ISSUE TITLE
Pushing DinD To DTR or Docker Hub

### ISSUE THREAD

**Issue by osobh** [jpetazzo/dind#91]
Lets say I create a dind container and inside this I can run docker to launch containers. After working awhile in this dind setup and creating container, I want to exit and push my finished dind container to the Docker Hub and then pull it back with everything still intact.

I remove the images locally and pull the dind image from docker hub to see if all my changes stick inside the container. I can see that config files and the like show up fine, But I don't see any of the containers that I had spawned inside the dind container. Is the push stripping all containers out or am i missing something critical with dind and pushing?

**Comment by jpetazzo** [comment]
That's because the images and containers are on a [volume](https://docs.docker.com/userguide/dockervolumes/) and as such they're not kept in images.

If you want to retain images and containers, you can change the Docker graph root (`--graph` option when starting the daemon) but be aware that trying to push that to the Hub would result in a really big image!
