### ISSUE TITLE
[QUESTION] usage of Docker for development

### ISSUE THREAD

**Issue by jeffersonbezerra** [jpetazzo/dind#93]
Hi, 

Each dev on my team has his own enviroment with java installation, maven, nodejs, heroku, apache and so on. In this case, we hope all dev uses the same versions.

I'm thinking about introduce Docker on my team workflow. 

Is this approach correct?
* Create one big Docker (called "**dev_tools**") container with all packages that everyone uses to develop: java, node, maven, ...; 
* Distribute this container ;
* Create containers that will run the applications on heroku and locally on dev;
* "dev_tools" init these containers that will run the applications on heroku;

Notes: heroku instalation requires docker instalation. So, if I need to run heroku on "dev_tools", I'll need to install docker inside de "dev_tools" container.

Any article related with this is welcome

**Comment by thaJeztah** [comment]
I think this is more a question for;

1) the #docker IRC channel on Freenode.
2) the forums: https://forums.docker.com/
3) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user

Without going in-depth, I'd really discourage building a large container with all those tools installed; Docker shines at splitting up your applications into smaller elements, e.g. a container that runs Node, a container that runs MySQL. As a nice extra, that allows you to use the official images from Docker Hub, so that you don't have to maintain all these versions.

**Comment by jpetazzo** [comment]
@jeffersonbezerra: regarding your last question —

> if I need to run heroku on "dev_tools", I'll need to install docker inside de "dev_tools" container.

I would recommend the approach described in [this blog post](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/), which is easier than having docker-in-docker.

Cheers,
